apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "sonar"
  namespace: "operations"
  annotations:
    kubernetes.io/tls-acme: "true"
    ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
  - hosts:
    - sonar.revatureops.com
    secretName: sonar-tls
  rules:
  - host: sonar.revatureops.com
    http:
      paths:
      - path: /
        backend:
          serviceName: sonar
          servicePort: 80
